export const AUTH_REQUEST = 'AUTH_REQUEST';
export const AUTH_REQUEST_GET_ID = 'AUTH_REQUEST_GET_ID';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_SUCCESS_GET_ID = 'AUTH_SUCCESS_GET_ID';
export const AUTH_ERROR = 'AUTH_ERROR';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
