version: '3'

services:
  db:
    image: postgres:10.7-alpine
    restart: always
    environment:
          POSTGRES_PASSWORD: pass
          POSTGRES_USER: user
          PGDATA: /var/lib/postgresql/data/pgdata
          POSTGRES_DB: training
    ports:
      - 8091
    volumes:
      - /postgres:/var/lib/postgresql/data

  spring-app:
    build: ./
    volumes:
      - /src:/usr/src/app
    ports:
      - 8090:8090
