version: '3'

services:
  db:
    image: postgres:10.7-alpine
    restart: always
    environment:
          POSTGRES_PASSWORD: pass
          POSTGRES_USER: user
          POSTGRES_DB: training
    ports:
<<<<<<< HEAD
      - 8091:5432
=======
      - 8091
    volumes:
      - /postgres:/var/lib/postgresql/data
>>>>>>> master

  spring-app:
    build: ./
    ports:
      - 8090:8090
