version: '3'

services:
  db:
    image: postgres:10.7-alpine
    restart: always
    environment:
          POSTGRES_PASSWORD: pass
          POSTGRES_USER: user
          POSTGRES_DB: training
    ports:
      - 8081:5432

  spring-app:
    build: ./
    ports:
      - 8090:8090
